### ISSUE TITLE
macOS 下无法登陆

### ISSUE THREAD

**Issue by corningsun** [trazyn/weweChat#147]
master 分支

`npm build`
`npm run dev`

控制台报错
```
[0] ℹ ｢wdm｣: Compiled successfully.
[1] TypeError: Cannot read property 'destroy' of undefined
[1]     at updateTray (/Users/sunkangning932/opt/weweChat/main.js:475:14)
[1]     at EventEmitter.<anonymous> (/Users/sunkangning932/opt/weweChat/main.js:545:13)
[1]     at emitTwo (events.js:126:13)
[1]     at EventEmitter.emit (events.js:214:7)
[1]     at WebContents.<anonymous> (/Users/sunkangning932/opt/weweChat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:286:13)
[1]     at emitTwo (events.js:126:13)
[1]     at WebContents.emit (events.js:214:7)
```

界面显示出二维码了

但是扫描二维码后在 `Scan successful` 界面卡住了，无法进入

**Comment by trazyn** [comment]
1.1.6试试

**Comment by Gmunoz72** [comment]
Whatsapp
