### ISSUE TITLE
Error: App version is not a valid semver version: "0.0" --npm run dev

### ISSUE THREAD

**Issue by iT-lijun** [trazyn/weweChat#155]
微信虽然能运行起来 但日志有**报错**  请各位**指导赐教**！
1. 开发环境：Ubuntu 18.04 、Node 8.11.3
2. 运行命令：**npm run dev**
3. 运行报错：libgconf-2.so.4: cannot open shared object file: No such file or directory 
4. 解决方法：**sudo apt-get install libgconf-2-4**
5. 再跑命令：**npm run dev**
6. 再次报错：(微信虽然能运行起来 但日志有**报错**)
> wewechat@1.1.6 dev /home/lijun/Desktop/Dev/weweChat-master
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[0] 
[0] > wewechat@1.1.6 hot-server /home/lijun/Desktop/Dev/weweChat-master
[0] > cross-env NODE_ENV=development node -r babel-register scripts/dev.js
[0] 
[1] 
[1] > wewechat@1.1.6 start-hot /home/lijun/Desktop/Dev/weweChat-master
[1] > cross-env HOT=1 NODE_ENV=development ./node_modules/.bin/electron -r babel-register -r babel-polyfill ./main
[1] 
[1] App threw an error during load
**[1] Error: App version is not a valid semver version: "0.0"
[1]     at newError (/home/lijun/Desktop/Dev/weweChat-master/node_modules/builder-util-runtime/src/index.ts:29:17)**
[1]     at new AppUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/AppUpdater.ts:180:13)
[1]     at new BaseUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/BaseUpdater.ts:12:5)
[1]     at new AppImageUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/AppImageUpdater.ts:15:5)
[1]     at _load_autoUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/main.ts:27:20)
[1]     at Object.get [as autoUpdater] (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/main.ts:35:28)
[1]     at Object.<anonymous> (/home/lijun/Desktop/Dev/weweChat-master/main.js:890:18)
[1]     at Object.<anonymous> (/home/lijun/Desktop/Dev/weweChat-master/main.js:944:3)
[1]     at Module._compile (module.js:642:30)
[1]     at loader (/home/lijun/Desktop/Dev/weweChat-master/node_modules/babel-register/lib/node.js:144:5)
[1] A JavaScript error occurred in the main process
[1] Uncaught Exception:
[1] Error: App version is not a valid semver version: "0.0"
[1]     at newError (/home/lijun/Desktop/Dev/weweChat-master/node_modules/builder-util-runtime/src/index.ts:29:17)
[1]     at new AppUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/AppUpdater.ts:180:13)
[1]     at new BaseUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/BaseUpdater.ts:12:5)
[1]     at new AppImageUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/AppImageUpdater.ts:15:5)
[1]     at _load_autoUpdater (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/main.ts:27:20)
[1]     at Object.get [as autoUpdater] (/home/lijun/Desktop/Dev/weweChat-master/node_modules/electron-updater/src/main.ts:35:28)
[1]     at Object.<anonymous> (/home/lijun/Desktop/Dev/weweChat-master/main.js:890:18)
[1]     at Object.<anonymous> (/home/lijun/Desktop/Dev/weweChat-master/main.js:944:3)
[1]     at Module._compile (module.js:642:30)
[1]     at loader (/home/lijun/Desktop/Dev/weweChat-master/node_modules/babel-register/lib/node.js:144:5)

**Comment by trazyn** [comment]
看起来是自动更新的原因，本地环境是没有`dev-app-update.yml`的，这个错误可以不用管

**Comment by iT-lijun** [comment]
@trazyn **thanks for your comments sincerely**
