### ISSUE TITLE
windows打包失败怎么办?

### ISSUE THREAD

**Issue by gclsoft** [trazyn/weweChat#163]
npm install 是ok
npm run dev也ok
npm run package-win 就报下面的错误, 试了十几遍都不行, 机器是winserver 2008:
```
Error : Unresolved node modules: auto-correct, bagpipe, colors, graceful-readlink
, giturl, npm, npm-request, npminstall, open, urllib
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\util\packag
eDependencies.ts:109:19
From previous event:
    at Collector.resolveUnresolvedHoisted (E:\crm\i\nginx\weweChat\node_modules\
electron-builder-lib\out\util\packageDependencies.js:206:11)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\util\packag
eDependencies.ts:85:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Collector.collect (E:\crm\i\nginx\weweChat\node_modules\electron-builder-
lib\out\util\packageDependencies.js:154:11)
    at computeDependencies (E:\crm\i\nginx\weweChat\node_modules\electron-builde
r-lib\src\util\packageDependencies.ts:50:26)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\util\packag
eDependencies.ts:45:28
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (E:\crm\i\nginx\weweChat\node_modules\electron-
builder-lib\out\util\packageDependencies.js:29:21)
    at Lazy (E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\util\
packageDependencies.ts:39:25)
    at Lazy.get value [as value] (E:\crm\i\nginx\weweChat\node_modules\lazy-val\
src\main.ts:18:23)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\util\yarn.t
s:120:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\out\ut
il\yarn.js:93:22)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\util\yarn.t
s:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at installOrRebuild (E:\crm\i\nginx\weweChat\node_modules\electron-builder-l
ib\out\util\yarn.js:31:21)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\packager.ts
:442:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (E:\crm\i\nginx\weweChat\node_modules\ele
ctron-builder-lib\out\packager.js:496:11)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\packager.ts
:356:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (E:\crm\i\nginx\weweChat\node_modules\electron-builder-l
ib\out\packager.js:432:11)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\packager.ts
:308:52
    at Generator.next (<anonymous>)
    at E:\crm\i\nginx\weweChat\node_modules\graceful-fs\graceful-fs.js:99:16
    at E:\crm\i\nginx\weweChat\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (E:\crm\i\nginx\weweChat\node_modules\electron-builder-li
b\out\packager.js:376:11)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib\src\packager.ts
:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (E:\crm\i\nginx\weweChat\node_modules\electron-builder-lib
\out\packager.js:332:11)
    at E:\crm\i\nginx\weweChat\node_modules\electron-builder\src\builder.ts:310:
40
    at Generator.next (<anonymous>)
From previous event:
    at _build (E:\crm\i\nginx\weweChat\node_modules\electron-builder\out\builder
.js:61:21)
    at build (E:\crm\i\nginx\weweChat\node_modules\electron-builder\src\builder.
ts:280:10)
    at then (E:\crm\i\nginx\weweChat\node_modules\electron-builder\src\cli\cli.t
s:48:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.args [as handler] (E:\crm\i\nginx\weweChat\node_modules\electron-b
uilder\src\cli\cli.ts:48:33)
    at Object.runCommand (E:\crm\i\nginx\weweChat\node_modules\yargs\lib\command
.js:235:44)
    at Object.parseArgs [as _parseArgs] (E:\crm\i\nginx\weweChat\node_modules\ya
rgs\yargs.js:1074:24)
    at Object.get [as argv] (E:\crm\i\nginx\weweChat\node_modules\yargs\yargs.js
:989:21)
    at Object.<anonymous> (E:\crm\i\nginx\weweChat\node_modules\electron-builder
\src\cli\cli.ts:42:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wewechat@1.1.7 package-win: `npm run build && build --win --projectDir
./dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wewechat@1.1.7 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-08-11T0
7_38_51_549Z-debug.log
```

**Comment by trazyn** [comment]
加个环境变量看看
`ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true`

**Comment by gclsoft** [comment]
谢谢,可以了!
