### ISSUE TITLE
TypeError: Class constructor BMF cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Papeone** [trazyn/weweChat#193]
helper.js?e101:299 Uncaught (in promise) TypeError: Class constructor BMF cannot be invoked without 'new'
    at eval (webpack-internal:///./src/js/utils/helper.js:339:42)
    at new Promise (<anonymous>)
    at Object.md5 (webpack-internal:///./src/js/utils/helper.js:338:16)
    at Chat._callee13$ (webpack-internal:///./src/js/stores/chat.js:1387:57)
    at tryCatch (webpack-internal:///./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (webpack-internal:///./src/js/stores/chat.js:377:191)
    at eval (webpack-internal:///./src/js/stores/chat.js:377:437)
    at new Promise (<anonymous>)

**Comment by Papeone** [comment]
change helper.js  line299

  md5: (file) => {
        const md = new MD5();
        return new Promise((resolve, reject) => {
            md.md5(file, (err, md5) => { resolve(err ? false : md5); }, progress => {});
        });
    }
browser-md5-file 升级改了api的原因

**Comment by evolutionjay** [comment]
hey 不更新么 ？ 老铁。

**Comment by Papeone** [comment]
> hey 不更新么 ？ 老铁。

第二条已经是解决方法了

**Comment by yurenchen000** [comment]
难受了好几天, 幸亏搜索了一下.
  什么时候能合进主线就好了.
