### ISSUE TITLE
Ubuntu181.0 无法运行

### ISSUE THREAD

**Issue by lpf-gavin** [trazyn/weweChat#196]
运行后出现：
9067 segmentation fault (core dumped)  /opt/wewechat/wewechat
请问怎么解决？

**Comment by abcfyk** [comment]
尝试执行 apt -f install

**Comment by jeebeans** [comment]
段错误 (核心已转储) 启动就报这样的错误,有办法修正么?

**Comment by mzr1996** [comment]
+1 无法使用，同为ubuntu18.10

**Comment by 9n** [comment]
+1 无法启动 kubuntu 18.10

**Comment by ZZZXXX0110** [comment]
+1 无法使用， Kubuntu 18.10

**Comment by ukhack** [comment]
+1

**Comment by JD1412** [comment]
same here

**Comment by Seven-Steven** [comment]
same here

**Comment by zzhiyi** [comment]
This is an upstream bug, see https://github.com/electron/electron/issues/13972 for details.
Update electron version to 2.0.8 and later should fix this. https://github.com/electron/electron/releases/tag/v2.0.8

Version after v2.0.8 also contains a lot of crash fix as well. So we might want to upgrade it to the latest version.

**Comment by AiRyunn** [comment]
still crash now

```shell
$ electron --version
v5.0.0
```

gdb:
```
GNU gdb (Ubuntu 8.2-0ubuntu1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from wewechat...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/wewechat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000b87650 in ?? ()
(gdb) bt
#0  0x0000000000b87650 in  ()
#1  0x00007ffff7d833e2 in node::http2::Http2Session::Callbacks::Callbacks(bool) () at /opt/wewechat/libnode.so
#2  0x00007ffff7d834a5 in  () at /opt/wewechat/libnode.so
#3  0x00007ffff7fe398a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe048, env=env@entry=0x7fffffffe058) at dl-init.c:72
#4  0x00007ffff7fe3a89 in call_init (env=0x7fffffffe058, argv=0x7fffffffe048, argc=1, l=<optimized out>) at dl-init.c:30
#5  0x00007ffff7fe3a89 in _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe048, env=0x7fffffffe058) at dl-init.c:119
#6  0x00007ffff7fd40ca in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in  ()
#8  0x00007fffffffe44b in  ()
#9  0x0000000000000000 in  ()
```

**Comment by zzhiyi** [comment]
Please use the build from source, it's fixed in the master branch. Electron on the host doesn't affect this app. I meant the bundled electron.

**Comment by PigeonAOA** [comment]
+1ubuntu20.04
