### ISSUE TITLE
Error: Generate the binary "npm run package-mac"

### ISSUE THREAD

**Issue by SevnChen** [trazyn/weweChat#6]
运行"npm run package-mac"时报错

```
npm ERR! missing script: package-mac

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sevn/.npm/_logs/2017-08-24T05_53_51_301Z-debug.log
```

2017-08-24T05_53_51_301Z-debug.log
``` log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package-mac' ]
2 info using npm@5.3.0
3 info using node@v8.1.1
4 verbose stack Error: missing script: package-mac
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:114:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:401:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:399:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:159:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:347:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:512:3)
5 verbose cwd /Users/sevn/Documents/003_Study/010_wechat/weweChat
6 verbose Darwin 16.7.0
7 verbose argv "/usr/local/Cellar/node/8.1.1/bin/node" "/usr/local/bin/npm" "run" "package-mac"
8 verbose node v8.1.1
9 verbose npm  v5.3.0
10 error missing script: package-mac
11 verbose exit [ 1, true ]

```

**Comment by SevnChen** [comment]
更新后好了。
