### ISSUE TITLE
ubuntu16.04  node  -v8.9.1  npm run package-linux错误

### ISSUE THREAD

**Issue by sxft1978** [trazyn/weweChat#75]
ubuntu16.04  node  -v8.9.1  npm run package-linux错误

**Comment by trazyn** [comment]
看看详细的报错信息

**Comment by sxft1978** [comment]
info it worked if it ends with ok
1 verbose cli [ '/home/wdt-1/opt/node-v8.9.1-linux-x64/bin/node',
1 verbose cli   '/home/wdt-1/opt/node-v8.9.1-linux-x64/lib/node_modules/cnpm/node_modules/.bin/npm',
1 verbose cli   '--userconfig=/home/wdt-1/.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=http://registry.npm.taobao.org',
1 verbose cli   'run',
1 verbose cli   'package-linux' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prepackage-linux', 'package-linux', 'postpackage-linux' ]
5 info lifecycle wewechat@1.1.4~prepackage-linux: wewechat@1.1.4
6 info lifecycle wewechat@1.1.4~package-linux: wewechat@1.1.4
7 verbose lifecycle wewechat@1.1.4~package-linux: unsafe-perm in lifecycle true
8 verbose lifecycle wewechat@1.1.4~package-linux: PATH: /home/wdt-1/opt/node-v8.9.1-linux-x64/lib/node_modules/cnpm/node_modules/npm/bin/node-gyp-bin:/home/wdt-1/weweChat/node_modules/.bin:/home/wdt-1/bin:/home/wdt-1/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/wdt-1/opt/jdk1.8.0_152/bin:/home/wdt-1/opt/jdk1.8.0_152/jre/bin:/home/wdt-1/opt/node-v8.9.1-linux-x64/bin
9 verbose lifecycle wewechat@1.1.4~package-linux: CWD: /home/wdt-1/weweChat
10 silly lifecycle wewechat@1.1.4~package-linux: Args: [ '-c',
10 silly lifecycle   'npm run build && rm -rf release && build --linux --projectDir ./dist' ]
11 silly lifecycle wewechat@1.1.4~package-linux: Returned: code: 1  signal: null
12 info lifecycle wewechat@1.1.4~package-linux: Failed to exec package-linux script
13 verbose stack Error: wewechat@1.1.4 package-linux: `npm run build && rm -rf release && build --linux --projectDir ./dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/wdt-1/opt/node-v8.9.1-linux-x64/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/wdt-1/opt/node-v8.9.1-linux-x64/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wewechat@1.1.4
15 verbose cwd /home/wdt-1/weweChat
16 verbose Linux 4.10.0-40-generic
17 verbose argv "/home/wdt-1/opt/node-v8.9.1-linux-x64/bin/node" "/home/wdt-1/opt/node-v8.9.1-linux-x64/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/home/wdt-1/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=http://registry.npm.taobao.org" "run" "package-linux"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error wewechat@1.1.4 package-linux: `npm run build && rm -rf release && build --linux --projectDir ./dist`
22 error Exit status 1
23 error Failed at the wewechat@1.1.4 package-linux script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sxft1978** [comment]
clone最新的

**Comment by trazyn** [comment]
错误是由于[error with sourcemaps](https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68)导致，已删除`devtool: 'source-map',`，删除本地的`node_modules`然后重新安装依赖，本地`build`成功

**Comment by sxft1978** [comment]
Installing app dependencies for linux:x64 to /home/wdt-1/weweChat/dist
Packaging for linux x64 using electron 1.8.1 to ../release/linux-unpacked
Building AppImage for arch x64
Building deb
Building rpm
Error: Exit code: 1. Command failed: /home/wdt-1/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/fpm -s dir -t rpm --architecture amd64 --name wewechat --force --after-install /tmp/temp-dir-Q5z7vU/2-after-install --after-remove /tmp/temp-dir-Q5z7vU/3-after-remove --description Unofficial WeChat client built with React, MobX and Electron. --maintainer undefined <var.darling@gmail.com> --vendor undefined <var.darling@gmail.com> --version 1.1.4 --package /home/wdt-1/weweChat/release/wewechat-1.1.4-linux-x86_64.rpm --url https://github.com/trazyn/weweChat#readme --rpm-os linux --depends libnotify --depends libappindicator --depends libXScrnSaver --license MIT /home/wdt-1/weweChat/release/linux-unpacked/=/opt/wewechat /home/wdt-1/weweChat/resource/128x128.png=/usr/share/icons/hicolor/128x128/apps/wewechat.png /home/wdt-1/weweChat/resource/16x16.png=/usr/share/icons/hicolor/16x16/apps/wewechat.png /home/wdt-1/weweChat/resource/24x24.png=/usr/share/icons/hicolor/24x24/apps/wewechat.png /home/wdt-1/weweChat/resource/32x32.png=/usr/share/icons/hicolor/32x32/apps/wewechat.png /home/wdt-1/weweChat/resource/48x48.png=/usr/share/icons/hicolor/48x48/apps/wewechat.png /home/wdt-1/weweChat/resource/64x64.png=/usr/share/icons/hicolor/64x64/apps/wewechat.png /home/wdt-1/weweChat/resource/96x96.png=/usr/share/icons/hicolor/96x96/apps/wewechat.png /tmp/temp-dir-Q5z7vU/5-wewechat.desktop=/usr/share/applications/wewechat.desktop

{:timestamp=>"2017-11-24T17:40:34.408892+0800", :message=>"Need executable 'rpmbuild' to convert dir to rpm", :level=>:error}

    at /home/wdt-1/weweChat/node_modules/builder-util/src/util.ts:109:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at exec (/home/wdt-1/weweChat/node_modules/builder-util/src/util.ts:77:3)
    at /home/wdt-1/weweChat/node_modules/electron-builder-lib/src/targets/fpm.ts:217:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/home/wdt-1/weweChat/node_modules/electron-builder-lib/out/targets/fpm.js:274:11)
    at default.each.it (/home/wdt-1/weweChat/node_modules/electron-builder-lib/src/platformPackager.ts:121:87)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at taskManager.addTask.default.map.then (/home/wdt-1/weweChat/node_modules/electron-builder-lib/src/platformPackager.ts:121:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/wdt-1/weweChat/node_modules/electron-builder-lib/src/platformPackager.ts:121:8)
    at /home/wdt-1/weweChat/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at LinuxPackager.pack (/home/wdt-1/weweChat/node_modules/electron-builder-lib/out/platformPackager.js:190:11)
    at /home/wdt-1/weweChat/node_modules/electron-builder-lib/src/packager.ts:326:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/home/wdt-1/weweChat/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager.doBuild (/home/wdt-1/weweChat/node_modules/electron-builder-lib/out/packager.js:393:11)
    at /home/wdt-1/weweChat/node_modules/electron-builder-lib/src/packager.ts:270:52
From previous event:
    at Packager._build (/home/wdt-1/weweChat/node_modules/electron-builder-lib/out/packager.js:337:11)
    at /home/wdt-1/weweChat/node_modules/electron-builder-lib/src/packager.ts:240:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/home/wdt-1/weweChat/node_modules/electron-builder-lib/out/packager.js:297:11)
    at /home/wdt-1/weweChat/node_modules/electron-builder/src/builder.ts:287:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/wdt-1/weweChat/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/wdt-1/weweChat/node_modules/electron-builder/src/builder.ts:257:10)
    at then (/home/wdt-1/weweChat/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/wdt-1/weweChat/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/wdt-1/weweChat/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/wdt-1/weweChat/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/wdt-1/weweChat/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/wdt-1/weweChat/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wewechat@1.1.4 package-linux: `npm run build && rm -rf release && build --linux --projectDir ./dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wewechat@1.1.4 package-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by trazyn** [comment]
`{:timestamp=>"2017-11-24T17:40:34.408892+0800", :message=>"Need executable 'rpmbuild' to convert dir to rpm", :level=>:error}`

`rpmbuild` 没有安装

**Comment by sxft1978** [comment]
谢谢,顺利完成
