### ISSUE TITLE
还是无法运行

### ISSUE THREAD

**Issue by joeyer** [trazyn/weweChat#81]
App threw an error during load
/Users/lzj/Desktop/weweChat-master/main.js:2
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/Users/lzj/.nvm/versions/node/v5.5.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/Users/lzj/.nvm/versions/node/v5.5.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:325:5)
    at Object.<anonymous> (/Users/lzj/.nvm/versions/node/v5.5.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:361:3)

**Comment by trazyn** [comment]
你的依赖有问题， `import`是`es6`语法，报错很明显你的依赖不对

**Comment by joeyer** [comment]
你好 我问一下，我要怎么去设置这个依赖，我node用5.5.0 npm用3.3.12 electron是用cnpm安装的1.7.9，然后现在一直卡在运行不起来上

**Comment by trazyn** [comment]
node请升级到8.0 删除`node_modules`然后`cnpm i`

**Comment by joeyer** [comment]
node 升级到9.2.0  npm 5.5.1 electron 1.7.9  但是还是运行不起来。由于本人才刚涉及到这块。所以还是想请教一下。具体一点该怎么弄

**Comment by trazyn** [comment]
其他的什么也不要做
```
$ git clone https://github.com/trazyn/weweChat.git --depth =1 
$ cd weweChat
$ cnpm i
$ npm run dev
```

**Comment by dongyanghe** [comment]
```
electron . 
```
这个命令确实运行不了

**Comment by dongyanghe** [comment]
@trazyn 可是不用electron . 那就没法调试了啊

**Comment by trazyn** [comment]
命令行直接`electron .`运行是需要你全局安装的才能作为命令使用，`package.json scrips`启动会找`node_modules/.bin`目录的`electron`，依赖比较大不确定国内网络是否能正常安装

**Comment by dongyanghe** [comment]
非常感谢，第一次使用electron，是我不太了解，已经能打开调试模式了，微信服务已经不能用了，我设想为weweChat专门弄个基于java的后台通讯服务，希望能实现。
